### ISSUE TITLE
windows_package broken in core in Chef 12.2.0+

### ISSUE THREAD

**Issue by btm** [chef/chef#3316]
Simple recipe:
```
package "7zip" do
  source 'c:/ruby/7z920-x64.msi'
end
```

Works on Chef 12.1.2:
```
PS C:\ruby> chef-apply install_7zip.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * windows_package[7zip] action install (up to date)
PS C:\ruby> chef-apply -v
Chef: 12.1.2
```

Fails on Chef 12.2.1:
```
PS C:\ruby> chef-apply -v
Chef: 12.2.1
PS C:\ruby> chef-apply install_7zip.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * windows_package[7zip] action install
    * No version specified, and no candidate version available for 7zip
    ================================================================================
    Error executing action `install` on resource 'windows_package[7zip]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No version specified, and no candidate version available for 7zip

    Resource Declaration:
    ---------------------
    # In install_7zip.rb

      1: package "7zip" do
      2:   source 'c:/ruby/7z920-x64.msi'
      3: end

    Compiled Resource:
    ------------------
    # Declared in install_7zip.rb:1:in `run_chef_recipe'

    windows_package("7zip") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "7zip"
      source "c:\\ruby\\7z920-x64.msi"
      version "9.20.00.0"
      timeout 600
      returns [0]
      declared_type :package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end

[2015-04-30T15:49:33-04:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-04-30T15:49:33-04:00] FATAL: Chef::Exceptions::Package: windows_package[7zip] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for 7zip
```

The regression appears to be caused by https://github.com/chef/chef/pull/3034.

**Comment by btm** [comment]
Fixed by #3317, in master, will be in the next release.

**Comment by mrwizard82d1** [comment]
I still see this issue running chef-client 12.3.0:

$ chef-client --local-mode --log_level info --runlist 'recipe[test-3316]'
[2015-06-15T11:28:48-05:00] WARN: No config file found or specified on command line, using command line options.
[2015-06-15T11:28:48-05:00] INFO: Auto-discovered chef repository at c:/cygwin64/home/ljones/professional/projects/scratch-chef
[2015-06-15T11:28:48-05:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at c:/cygwin64/home/ljones/professional/projects/scratch-chef
  One version per cookbook

Starting Chef Client, version 12.3.0
[2015-06-15T11:28:52-05:00] INFO: *** Chef 12.3.0 ***
[2015-06-15T11:28:52-05:00] INFO: Chef-client pid: 13308
[2015-06-15T11:29:08-05:00] INFO: Setting the run_list to [#<Chef::RunList::RunListItem:0x235c578 @version=nil, @type=:recipe, @name="test-3316">] from CLI options
[2015-06-15T11:29:08-05:00] INFO: Run List is [recipe[test-3316]]
[2015-06-15T11:29:08-05:00] INFO: Run List expands to [test-3316]
[2015-06-15T11:29:08-05:00] INFO: Starting Chef Run for HOUL0050.olf.com
[2015-06-15T11:29:08-05:00] INFO: Running start handlers
[2015-06-15T11:29:08-05:00] INFO: Start handlers complete.
[2015-06-15T11:29:08-05:00] INFO: HTTP Request Returned 404 Not Found: Object not found:
resolving cookbooks for run list: ["test-3316"]
[2015-06-15T11:29:08-05:00] INFO: Loading cookbooks [test-3316@0.1.0]
[2015-06-15T11:29:08-05:00] INFO: Removing cookbooks/ra/Berksfile from the cache; its cookbook is no longer needed on this client.
[2015-06-15T11:29:08-05:00] INFO: Removing cookbooks/ra/chefignore from the cache; its cookbook is no longer needed on this client.
[2015-06-15T11:29:08-05:00] INFO: Removing cookbooks/ra/metadata.rb from the cache; its cookbook is no longer needed on this client.
[2015-06-15T11:29:08-05:00] INFO: Removing cookbooks/ra/README.md from the cache; its cookbook is no longer needed on this client.
[2015-06-15T11:29:08-05:00] INFO: Removing cookbooks/ra/recipes/default.rb from the cache; its cookbook is no longer needed on this client.
[2015-06-15T11:29:08-05:00] INFO: Removing cookbooks/ra/.gitignore from the cache; its cookbook is no longer needed on this client.
[2015-06-15T11:29:09-05:00] INFO: Removing cookbooks/ra/.kitchen.yml from the cache; its cookbook is no longer needed on this client. Synchronizing Cookbooks:
[2015-06-15T11:29:09-05:00] INFO: Storing updated cookbooks/test-3316/.kitchen.yml in the cache.
[2015-06-15T11:29:09-05:00] INFO: Storing updated cookbooks/test-3316/.gitignore in the cache.
[2015-06-15T11:29:09-05:00] INFO: Storing updated cookbooks/test-3316/Berksfile in the cache.
[2015-06-15T11:29:09-05:00] INFO: Storing updated cookbooks/test-3316/metadata.rb in the cache.
[2015-06-15T11:29:09-05:00] INFO: Storing updated cookbooks/test-3316/recipes/default.rb in the cache.
[2015-06-15T11:29:09-05:00] INFO: Storing updated cookbooks/test-3316/chefignore in the cache.
[2015-06-15T11:29:09-05:00] INFO: Storing updated cookbooks/test-3316/README.md in the cache.
  - test-3316
Compiling Cookbooks...
Converging 1 resources
Recipe: test-3316::default
  * windows_package[7zip] action install[2015-06-15T11:29:09-05:00] INFO: Processing windows_package[7zip] action install (test-3316::default line 7)

    * No version specified, and no candidate version available for 7zip
    ================================================================================
    Error executing action `install` on resource 'windows_package[7zip]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No version specified, and no candidate version available for 7zip

    Resource Declaration:
    ---------------------
    # In c:/cygwin64/home/ljones/.chef/local-mode-cache/cache/cookbooks/test-3316/recipes/default.rb

      7: package "7zip" do
      8:   source 'c:/cygwin64/home/ljones/professional/software/devtools/7-zip/7z938-x64.msi'
      9: end

    Compiled Resource:
    ------------------
    # Declared in c:/cygwin64/home/ljones/.chef/local-mode-cache/cache/cookbooks/test-3316/recipes/default.rb:7:in `from_file'

    windows_package("7zip") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "7zip"
      source "c:\\cygwin64\\home\\ljones\\professional\\software\\devtools\\7-zip\\7z938-x64.msi"
      version "9.38.00.0"
      timeout 600
      returns [0]
      declared_type :package
      cookbook_name "test-3316"
      recipe_name "default"
    end

[2015-06-15T11:29:09-05:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-06-15T11:29:09-05:00] ERROR: Running exception handlers
Running handlers complete
[2015-06-15T11:29:09-05:00] ERROR: Exception handlers complete
[2015-06-15T11:29:09-05:00] FATAL: Stacktrace dumped to c:/cygwin64/home/ljones/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 20.7278 seconds
[2015-06-15T11:29:09-05:00] FATAL: Chef::Exceptions::Package: windows_package[7zip] (test-3316::default line 7) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for 7zip

**Comment by jdmundrawala** [comment]
You should try a 12.4.0 RC. The fix was not in 12.3.
https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-12.4.0-rc.2-1.msi

**Comment by mrwizard82d1** [comment]
Thanks, jdmundrawala. Installing this release worked.

Does a version of the chef-dk exist that bundles this version of the client?

Have a great day!

**Comment by n1t1nv3rma** [comment]
Hi there, is there any workaround for this issue for Chef < 12.4 ? It seems to works first time but fails subsequently? Perhaps set the property "ignore_failure" to "true" !

**Comment by Jakauppila** [comment]
I would be interested in a work around as well. Encountering this in AWS OpsWorks, which is currently limited to v12.2.1.

**Comment by smurawski** [comment]
@Jakauppila You can use `windows_package` from the windows cookbook to work around this.

**Comment by Jakauppila** [comment]
@smurawski Yep, I did try that earlier today and worked great, thanks.
