### ISSUE TITLE
Warnings should be confined to fused custom resources and not libraries

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#4334]
Lots and lots of SPAM messages using current runit cookbook.  I believe these are all false alarms as runit is not using custom resources and are using libraries split between resources and providers.

```
  * runit_service[public-dnscache] action enable/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:76:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:74:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:76:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:74:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:76:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/public-dnscache] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:76:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:84:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:82:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:84:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:82:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:84:in `block (2 levels) in <class:RunitService>': property group is declared in both template[/etc/sv/public-dnscache/run] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:84:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:97:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:95:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:97:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:95:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:97:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/public-dnscache/log] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:97:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:104:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:102:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:104:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:102:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:104:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/public-dnscache/log/main] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:104:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:112:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:110:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:112:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:110:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:112:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/var/log/public-dnscache] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:112:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:120:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:118:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:120:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:118:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:120:in `block (2 levels) in <class:RunitService>': property group is declared in both template[/etc/sv/public-dnscache/log/config] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:120:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:145:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:143:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:145:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:143:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:145:in `block (2 levels) in <class:RunitService>': property group is declared in both template[/etc/sv/public-dnscache/log/run] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:145:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:160:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:158:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:160:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:158:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:160:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/public-dnscache/env] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:160:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:208:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:206:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:208:in `block (2 levels) in <class:RunitService>'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:206:in `block in <class:RunitService>'
(eval):2:in `block in action_create'
(eval):2:in `action_create'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:280:in `block in <class:RunitService>'
(eval):2:in `block in action_enable'
(eval):2:in `action_enable'
/opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
[2015-12-20T10:39:48-08:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:208:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/public-dnscache/control] and #<Chef::Provider::RunitService:0x00000005ace9a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:208:in `block (2 levels) in <class:RunitService>'
```

**Comment by lamont-granquist** [comment]
@jkeiser messy fallout from trying to catch the scope issues...

**Comment by coderanger** [comment]
Confirmed that I'm getting a ton of these too, and all are false alarms.

**Comment by jkeiser** [comment]
The above PR should fix this ^^

**Comment by petecheslock** [comment]
hey @lamont-granquist are you no longer seeing these errors with chef `1.7.2`? I updated a test kitchen node and am still seeing those errors pop up on a fresh node and upgraded node.

```
          * ruby_block[restart_service] action run[2016-02-12T20:55:14+00:00] WARN: /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:75:in `block (2 levels
) in <class:RunitService>': property owner is declared in both directory[/etc/sv/chef-client] and #<Chef::Provider::RunitService:0x0000000c511c68>. Use new_resource.owner instead
. At /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:75:in `block (2 levels) in <class:RunitService>'
       [2016-02-12T20:55:14+00:00] WARN: /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:76:in `block (2 levels) in <class:RunitService>': property group i
s declared in both directory[/etc/sv/chef-client] and #<Chef::Provider::RunitService:0x0000000c511c68>. Use new_resource.group instead. At /tmp/kitchen/cache/cookbooks/runit/libr
aries/provider_runit_service.rb:76:in `block (2 levels) in <class:RunitService>'
       [2016-02-12T20:55:14+00:00] WARN: /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:83:in `block (2 levels) in <class:RunitService>': property owner i
s declared in both template[/etc/sv/chef-client/run] and #<Chef::Provider::RunitService:0x0000000c511c68>. Use new_resource.owner instead. At /tmp/kitchen/cache/cookbooks/runit/l
ibraries/provider_runit_service.rb:83:in `block (2 levels) in <class:RunitService>'
       [2016-02-12T20:55:14+00:00] WARN: /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:84:in `block (2 levels) in <class:RunitService>': property group i
s declared in both template[/etc/sv/chef-client/run] and #<Chef::Provider::RunitService:0x0000000c511c68>. Use new_resource.group instead. At /tmp/kitchen/cache/cookbooks/runit/l
ibraries/provider_runit_service.rb:84:in `block (2 levels) in <class:RunitService>'
```

**Comment by gretel** [comment]
samesame here in regards to what @petecheslock sais above.

**Comment by lamont-granquist** [comment]
confirmed, tons of warning spam

**Comment by charlesjohnson** [comment]
Anybody seeing this outside of the runit cookbook resources?

**Comment by coderanger** [comment]
Yes ![rake spec output](http://i.coderanger.net/taAwM.png)

**Comment by charlesjohnson** [comment]
Thanks! If anyone has a reproduction case handy in cookbook form it'll speed things along, but it's not necessary.

**Comment by coderanger** [comment]
Clone https://github.com/poise/application_git, run `bundle install`, and then `rake spec` and you'll see the lovely output from above.

**Comment by randomcamel** [comment]
Related: https://github.com/chef/chef/issues/4672

**Comment by randomcamel** [comment]
Besides [the existing checks](https://github.com/chef/chef/blob/4eae1928300d36957b58b7eceabc81f44e9303e0/lib/chef/property.rb#L319), is it possible to further distinguish between cases where the warning should or should not be issued? It seems like it's asking for some examination of the call stack, which is unsavory as well as unreliable.

Would it be sufficient to just roll up those warnings so they only occur once per instance?

**Comment by coderanger** [comment]
@randomcamel No, that would not be sufficient.

**Comment by randomcamel** [comment]
I need to cook up a spec, but this seems to solve the problem: https://github.com/chef/chef/pull/4684

**Comment by randomcamel** [comment]
Fixed by #4684.

**Comment by coderanger** [comment]
Confirming my cookbooks seem to be much happier. Thanks!
