### ISSUE TITLE
Chef::Exceptions::Win32APIError: Incorrect function in 12.19.37 

### ISSUE THREAD

**Issue by paulhanssen** [chef/chef#5859]
## Description

Using Chef to provision a Windows 10 Vagrant VM, the following error happens:

```
==> default: [2017-03-03T00:52:21-08:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at C:/vagrant-chef/40f37b0b37411f684c790d2f357549b5, C:/vagrant-chef/588f404ca24d5ad8d60e3538d13cf04d
==> default:   One version per cookbook
...
==> default: Starting Chef Client, version 12.19.36
==> default: [2017-03-03T00:52:21-08:00] INFO: *** Chef 12.19.36 ***
==> default: [2017-03-03T00:52:21-08:00] INFO: Platform: x64-mingw32
...
==> default: [2017-03-03T00:52:43-08:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/winbuild4885305
==> default: [2017-03-03T00:52:43-08:00] ERROR: #<Chef::Exceptions::Win32APIError: Incorrect function.
==> default: ---- Begin Win32 API output ----
==> default: System Error Code: 1
==> default: System Error Message: Incorrect function.
==> default: ---- End Win32 API output ----
==> default: >
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/win32/error.rb:81:in `raise!'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/win32/security.rb:541:in `set_named_security_info'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/win32/security/securable_object.rb:91:in `block in owner='
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/win32/security.rb:620:in `with_privileges'
...
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/bin/chef-client:26:in `<top (required)>'
==> default: C:/opscode/chef/bin/chef-client:68:in `load'
==> default: C:/opscode/chef/bin/chef-client:68:in `<main>'
==> default: [2017-03-03T00:52:43-08:00] INFO: HTTP Request Returned 500 Internal Server Error: error
```

## Chef Version

Chef 12.19.37 and Chef-Zero 5.3.0, orchestrated through Vagrant 1.9.2

## Platform Version

Windows 10 Build 14393.rs1_release.160715-1616 (VM guest of Mac OS X 10.11)

## Replication Case

Boot a new Windows 10 node with the above platform version. A basic Vagrant file is attached to the gist below.

## Client Output

See gist: https://gist.github.com/paulhanssen/f058bb950d85768e3633fca81d7a3ab8

## Stacktrace

See gist above

Please let me know if there is a better repo in order to raise this issue at.

**Comment by dustinhperkins** [comment]
Getting the exact same error using the same chef version and also on windows 10.

**Comment by sngz** [comment]
getting same error on windows server 2016 standard edition

**Comment by piyushawasthi** [comment]
@paulhanssen, @sngz - I have not able to reproduce the issue while creating windows 2016 guest using vagrant. Also tried to provision with both chef_solo and chef_zero. 
```
Vagrant version: 1.8.0
Chef version: 12.19.36
```
**Note**:  `Chef 12.19.37` isn't available. So I couldn't test using that version.

I faced an issue while using the shared Vagrantfile. It's enabling the Berkshelf plugin without `berksfile_path`, that must be set.
https://gist.github.com/paulhanssen/f058bb950d85768e3633fca81d7a3ab8#file-vagrantfile-excerpt-L37

I have created gist for Vagrantfile, which worked successfully:
https://gist.github.com/piyushawasthi/0294125a3ea20fcfe02bb98dda16205b

**Comment by NimishaS** [comment]
@paulhanssen , @sngz any updates here?

**Comment by paulhanssen** [comment]
Thanks for looking at this @piyushawasthi 

It's still failing with Windows 10, as opposed to Windows 2016 guest.

Specifying Chef 12.10.24 in the Vagrantfile when provisioning Chef Zero avoids the error.

When I have some more time I can check against Windows 2016.

**Comment by piyushawasthi** [comment]
@paulhanssen - I am not able to reproduce the issue while creating windows 2010 guest using vagrant. Also tried to provision with both chef_solo and chef_zero.

Vagrant version: 1.9.3
Chef version: 13.0.118

Please check here: https://github.com/piyushawasthi/vagrant_chef_zero_windows_10

**Comment by sngz** [comment]
i haven't tried again in a while but I pulled out a backup copy of the vagrantfile and reran it and its no longer producing the exact same error and I'm getting another error now, I think i'll open another ticket for that.

**Comment by piyushawasthi** [comment]
@sngz : Please share your Vagrantfile and error.

**Comment by sngz** [comment]
it ended up being a vagrant error and unrelated to chef

**Comment by NimishaS** [comment]
@paulhanssen , @btm, can you please close this issue if it no longer persists?

**Comment by btm** [comment]
@sngz what was the vagrant error?

@paulhanssen It seems related to synced folders. Is there anything special about where the cookbooks live on your OS X host? Are they on a network share or a USB drive or anything?

**Comment by paulhanssen** [comment]
Hi @btm @NimishaS this is my current host environment on Mac OS X 10.11 "El Capitan":

```
~$ chef --version
Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0

~$ vagrant version
Installed Version: 1.9.4
Latest Version: 1.9.4

You're running an up-to-date version of Vagrant!

~$ VBoxManage --version
5.1.22r115126
```

This is the error I receive when I bootstrap a Vagrantfile using the ```chef.version = 'latest'```:

```
==> default: [2017-05-03T21:07:38-07:00] INFO: HTTP Request Returned 500 Internal Server Error: error
==> default:
==> default: ================================================================================
==> default: Chef encountered an error attempting to load the node data for "winbuild4938705"
==> default: ================================================================================
==> default: Unknown Server Error:
==> default: ---------------------
==> default: The server had a fatal error attempting to load the node data.
==> default:
==> default: Server Response:
==> default: ----------------
==> default: Exception raised! #<Chef::Exceptions::Win32APIError: Incorrect function.
==> default: ---- Begin Win32 API output ----
==> default: System Error Code: 1
==> default: System Error Message: Incorrect function.
==> default: ---- End Win32 API output ----
==> default: >
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/win32/error.rb:81:in `raise!'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/win32/security.rb:541:in `set_named_security_info'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/win32/security/securable_object.rb:91:in `block in owner='
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/win32/security.rb:620:in `with_privileges'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/win32/security/securable_object.rb:90:in `owner='
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/chef_fs/file_system/repository/nodes_dir.rb:50:in `create_child'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/chef_fs/file_system/multiplexed_dir.rb:57:in `create_child'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:255:in `block in create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:794:in `with_parent_dir'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:253:in `create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:34:in `block in create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:113:in `fix_exceptions'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:33:in `create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/rest_base.rb:180:in `create_data'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/endpoints/rest_list_endpoint.rb:31:in `post'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/endpoints/nodes_endpoint.rb:24:in `post'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/rest_base.rb:59:in `call'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/rest_router.rb:24:in `call'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/server.rb:663:in `block in app'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/server.rb:335:in `handle_socketless_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/socketless_server_map.rb:87:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/socketless_server_map.rb:33:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/http/socketless_chef_zero_client.rb:154:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/http.rb:375:in `block in send_http_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/http.rb:407:in `block in retrying_http_errors'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/http.rb:405:in `loop'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/http.rb:405:in `retrying_http_errors'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/http.rb:368:in `send_http_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/http.rb:149:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/http.rb:131:in `post'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/node.rb:610:in `create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/node.rb:568:in `rescue in find_or_create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/node.rb:564:in `find_or_create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:470:in `load_node'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:270:in `run'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:59:in `run'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/bin/chef-client:26:in `<top (required)>'
==> default: C:/opscode/chef/bin/chef-client:69:in `load'
==> default: C:/opscode/chef/bin/chef-client:69:in `<main>'
==> default: System Info:
==> default: ------------
==> default: chef_version=13.0.118
==> default: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
==> default: program_name=C:/opscode/chef/bin/chef-client
==> default: executable=C:/opscode/chef/bin/chef-client
```

However, when I revert to ```chef.version = '12.10.24'``` everything works fine.

This is Windows 10 (as above). I can't comment to Windows Server 2016 yet.

Cheers

**Comment by btm** [comment]
@paulhanssen can you share complete logs? or look to confirm what sync mechanism is being used?

**Comment by piyushawasthi** [comment]
@paulhanssen, I have verified on Mac OS X 10.11 "El Capitan" and it's working for me.

Host: OS X EI Caption (Version: 10.11.6)

**Comment by piyushawasthi** [comment]
@paulhanssen, I have verified on Mac OS X 10.11 "El Capitan" and it's working for me.

Host: OS X EI Caption (Version: 10.11.6)
Vagrant version: 1.9.5
Guest VM: Windows 10 Enterprise 2016 LTSB Evaluation

On Guest chef-client version: 13.0.118
![done](https://cloud.githubusercontent.com/assets/6093252/26254341/d8bb1a4e-3cd3-11e7-88c3-73a894bbb938.png)

**Comment by NimishaS** [comment]
![done](https://cloud.githubusercontent.com/assets/1298875/26256535/ee04f594-3cda-11e7-9344-eb05ed711e3d.png)

Please refer this screenshot for @piyushawasthi 's comment.

**Comment by NimishaS** [comment]
@paulhanssen , any updates on this?

**Comment by paulhanssen** [comment]
Still experiencing it on my host - El Capitan 10.11.6, with vagrant 1.9.5 and Chef 1.3.43.

My base box was built from packer using a Windows 10 Enterprise ISO (with versions I've stated previously).

I'll close and let the next person open it.

**Comment by NimishaS** [comment]
@paulhanssen , as @btm mentioned [here](https://github.com/chef/chef/issues/5859#issuecomment-301136303), please share complete logs since your issue is still not resolved.
There's one more thing that can be tried. In case you are passing any cookbooks in the runlist, please try passing a simple cookbook e.g. `getting-started` instead of that. This will confirm that the runlist is not causing any issue.

**Comment by paulhanssen** [comment]
Hi @NimishaS,

I have shared full logs :) ... they are attached as a gist to my original post.

This is the box I used: https://atlas.hashicorp.com/jhakonen/boxes/windows-10-n-pro-en-x86_64, which is built from this repo: https://github.com/joefitzgerald/packer-windows.

The error still appears with the latest stable ChefDK 1.4.3 for Chef version 13.1.31, but does not appear for chef version 12.10.24. The provisioning does not even get to the executing the recipes.

Regards

```
paul.hanssen$ vagrant up
Hostname: winbase49630576
==> default: VM not created. Moving on...
Hostname: winbase49630576
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'jhakonen/windows-10-n-pro-en-x86_64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'jhakonen/windows-10-n-pro-en-x86_64'
    default: URL: https://atlas.hashicorp.com/jhakonen/windows-10-n-pro-en-x86_64
==> default: Adding box 'jhakonen/windows-10-n-pro-en-x86_64' (v1.0.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/jhakonen/boxes/windows-10-n-pro-en-x86_64/versions/1.0.0/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
==> default: Successfully added box 'jhakonen/windows-10-n-pro-en-x86_64' (v1.0.0) for 'virtualbox'!
    default: The Berkshelf shelf is at "/Users/paul.hanssen/.berkshelf/vagrant-berkshelf/shelves/berkshelf20170601-43421-1ocw4pt-default"
==> default: Sharing cookbooks with VM
==> default: Importing base box 'jhakonen/windows-10-n-pro-en-x86_64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'jhakonen/windows-10-n-pro-en-x86_64' is up to date...
==> default: Setting the name of the VM: winbase49630576
==> default: Updating Vagrant's Berkshelf...
==> default: Resolving cookbook dependencies...
==> default: Fetching 'sf_windows' from source at ../../Chef-Recipes/cookbooks/sf_windows
==> default: Fetching cookbook index from https://supermarket.chef.io...
==> default: Using boxstarter (1.1.7)
==> default: Using sf_windows (0.2.17) from source at ../../Chef-Recipes/cookbooks/sf_windows
==> default: Vendoring boxstarter (1.1.7) to /Users/paul.hanssen/.berkshelf/vagrant-berkshelf/shelves/berkshelf20170601-43421-1ocw4pt-default/boxstarter
==> default: Vendoring sf_windows (0.2.17) to /Users/paul.hanssen/.berkshelf/vagrant-berkshelf/shelves/berkshelf20170601-43421-1ocw4pt-default/sf_windows
==> default: Using hostname "winbase49630576" as node name for Chef...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:55985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
Sorry, don't know how to check guest version of Virtualbox Guest Additions on this platform. Stopping installation.
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.0.26
    default: VirtualBox Version: 5.1
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/paul.hanssen/dev/vagrant-vms/win10
    default: C:/vagrant-chef/f1a26955b920435fdc9d0fac1f307a6d/roles => /Users/paul.hanssen/dev/Chef-Recipes/roles
    default: C:/vagrant-chef/fcc85b412a9959f98aa7c28c34cb8645/nodes => /Users/paul.hanssen/dev/Chef-Recipes/nodes
    default: C:/vagrant-chef/7ac1a23373df387bd99c34fba9d0491f/data_bags => /Users/paul.hanssen/dev/Chef-Recipes/data_bags
    default: C:/vagrant-chef/aa454d6e62d4401175322a0147364197/cookbooks => /Users/paul.hanssen/.berkshelf/vagrant-berkshelf/shelves/berkshelf20170601-43421-1ocw4pt-default
    default: C:/vagrant-chef/588f404ca24d5ad8d60e3538d13cf04d/cookbooks => /Users/paul.hanssen/dev/Chef-Recipes/cookbooks
    default: C:/vagrant-chef/557bea3d4194367b084422bcbcfec87d/environments => /Users/paul.hanssen/dev/Chef-Recipes/environments
==> default: Running provisioner: chef_zero...
    default: Installing Chef (latest)...
==> default: Generating chef JSON and uploading...
==> default: Running chef-client (local-mode)...
==> default: [2017-06-01T01:58:05-07:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at C:/vagrant-chef/aa454d6e62d4401175322a0147364197, C:/vagrant-chef/588f404ca24d5ad8d60e3538d13cf04d
==> default:   One version per cookbook
==> default:   data_bags at C:/vagrant-chef/7ac1a23373df387bd99c34fba9d0491f/data_bags
==> default:   environments at C:/vagrant-chef/557bea3d4194367b084422bcbcfec87d/environments
==> default:   roles at C:/vagrant-chef/f1a26955b920435fdc9d0fac1f307a6d/roles
==> default:   nodes at C:/vagrant-chef/fcc85b412a9959f98aa7c28c34cb8645/nodes
==> default: Starting Chef Client, version 13.1.31
==> default: [2017-06-01T01:58:05-07:00] INFO: *** Chef 13.1.31 ***
==> default: [2017-06-01T01:58:05-07:00] INFO: Platform: x64-mingw32
==> default: [2017-06-01T01:58:05-07:00] INFO: Chef-client pid: 1048
==> default: [2017-06-01T01:58:05-07:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
==> default: [2017-06-01T01:58:09-07:00] ERROR: #<Chef::Exceptions::Win32APIError: Incorrect function.
==> default: ---- Begin Win32 API output ----
==> default: System Error Code: 1
==> default: System Error Message: Incorrect function.
==> default: ---- End Win32 API output ----
==> default: >
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/win32/error.rb:81:in `raise!'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/win32/security.rb:541:in `set_named_security_info'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/win32/security/securable_object.rb:91:in `block in owner='
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/win32/security.rb:620:in `with_privileges'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/win32/security/securable_object.rb:90:in `owner='
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/chef_fs/file_system/repository/nodes_dir.rb:50:in `create_child'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/chef_fs/file_system/multiplexed_dir.rb:57:in `create_child'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:255:in `block in create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:794:in `with_parent_dir'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:253:in `create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:34:in `block in create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:113:in `fix_exceptions'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:33:in `create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/rest_base.rb:180:in `create_data'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/endpoints/rest_list_endpoint.rb:31:in `post'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/endpoints/nodes_endpoint.rb:24:in `post'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/rest_base.rb:59:in `call'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/rest_router.rb:24:in `call'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/server.rb:663:in `block in app'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/server.rb:335:in `handle_socketless_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/socketless_server_map.rb:87:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.0.0/lib/chef_zero/socketless_server_map.rb:33:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http/socketless_chef_zero_client.rb:154:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:375:in `block in send_http_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:407:in `block in retrying_http_errors'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:405:in `loop'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:405:in `retrying_http_errors'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:368:in `send_http_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:149:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:131:in `post'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/node.rb:610:in `create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/node.rb:568:in `rescue in find_or_create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/node.rb:564:in `find_or_create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/client.rb:470:in `load_node'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/client.rb:270:in `run'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application.rb:59:in `run'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/bin/chef-client:26:in `<top (required)>'
==> default: C:/opscode/chef/bin/chef-client:58:in `load'
==> default: C:/opscode/chef/bin/chef-client:58:in `<main>'
==> default: [2017-06-01T01:58:09-07:00] INFO: HTTP Request Returned 500 Internal Server Error: error
==> default:
==> default: ================================================================================
```
