### ISSUE TITLE
error while cleaning old files.

### ISSUE THREAD

**Issue by thommay** [chef/chef#6061]
@coredump reported on hangops that when syncing with a policyfile, they'd see:
`Error Syncing Cookbooks: NoMethodError: private method 'select' called for nil:NilClass`

<details>

```
coredump@bee ❯ kitchen converge
-----> Starting Kitchen (v1.15.0)
-----> Creating <default-ubuntu-1204-docker>...
-----> Converging <default-ubuntu-1204-vagrant>...
       Creating kitchen sandbox in /Users/coredump/.dokken/kitchen_sandbox/da70452846-default-ubuntu-1204-vagrant
       Updating policy lock using `chef update`
       Building policy default
       Expanded run list: recipe[yum], recipe[apt], recipe[poise-hoist], recipe[vox-app::test_scaffold], recipe[bananastand-app::db], recipe[bananastand-app::default], recipe[bananastand-app::nginx], recipe[bananastand-app::opencv], recipe[bananastand-app::redis], recipe[bananastand-app::vox_app_update]
       Caching Cookbooks...
       Using      yum             3.13.0
       Using      apt             2.9.2
       Using      poise-hoist     1.1.0
       Installing vox-app         0.5.1
       Installing bananastand-app 0.3.2
       Using      brightbox-ruby  1.0.0
       Using      git             4.0.2
       Using      logrotate       1.5.0
       Using      nginx           2.7.6
       Using      percona         0.15.5
       Using      redisio         2.5.0
       Installing vox-unicorn     0.3.0
       Installing vox-percona     0.1.26
       Using      runit           1.8.0
       Using      ulimit          0.4.0
       Using      build-essential 2.4.0
       Using      openssl         7.0.1
       Using      seven_zip       2.0.2
       Using      mingw           2.0.0
       Using      windows         2.0.2
       Using      bluepill        2.4.3
       Using      ohai            2.1.0
       Using      yum-epel        0.7.1
       Using      7-zip           1.0.2
       Using      rsyslog         6.0.1
       Using      packagecloud    0.3.0
       Using      dmg             3.1.1

       Lockfile written to /Users/coredump/Vox/vox-chef-repo/cookbooks/bananastand-app/test/policies/default.lock.json
       Policy revision id: 5cb006c6fff2a3d3eca9981ea3a1be9c8849a8f7a08b71ee2b1c1ff57c4b3f6a
       Installing cookbooks for Policyfile /Users/coredump/Vox/vox-chef-repo/cookbooks/bananastand-app/test/policies/default.rb using `chef install`
       Installing cookbooks from lock
       Using      yum             3.13.0
       Using      apt             2.9.2
       Using      poise-hoist     1.1.0
       Installing vox-app         0.5.1
       Installing bananastand-app 0.3.2
       Using      brightbox-ruby  1.0.0
       Using      git             4.0.2
       Using      logrotate       1.5.0
       Using      nginx           2.7.6
       Using      percona         0.15.5
       Using      redisio         2.5.0
       Installing vox-unicorn     0.3.0
       Installing vox-percona     0.1.26
       Using      runit           1.8.0
       Using      ulimit          0.4.0
       Using      build-essential 2.4.0
       Using      openssl         7.0.1
       Using      seven_zip       2.0.2
       Using      mingw           2.0.0
       Using      windows         2.0.2
       Using      bluepill        2.4.3
       Using      ohai            2.1.0
       Using      yum-epel        0.7.1
       Using      7-zip           1.0.2
       Using      rsyslog         6.0.1
       Using      packagecloud    0.3.0
       Using      dmg             3.1.1
       Preparing dna.json
       Exporting cookbook dependencies from Policyfile /Users/coredump/.dokken/kitchen_sandbox/da70452846-default-ubuntu-1204-vagrant...
       Exported policy 'default' to /Users/coredump/.dokken/kitchen_sandbox/da70452846-default-ubuntu-1204-vagrant

       To converge this system with the exported policy, run:
         cd /Users/coredump/.dokken/kitchen_sandbox/da70452846-default-ubuntu-1204-vagrant
         chef-client -z
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (12.19.36)
       Transferring files to <default-ubuntu-1204-vagrant>
       [2017-04-13T16:29:58+00:00] INFO: Forking chef instance to converge...
       Starting Chef Client, version 12.19.36
       [2017-04-13T16:29:58+00:00] INFO: *** Chef 12.19.36 ***
       [2017-04-13T16:29:58+00:00] INFO: Platform: x86_64-linux
       [2017-04-13T16:29:58+00:00] INFO: Chef-client pid: 2223
       Using policy 'default' at revision '5cb006c6fff2a3d3eca9981ea3a1be9c8849a8f7a08b71ee2b1c1ff57c4b3f6a'
       [2017-04-13T16:29:59+00:00] INFO: Run List is [["recipe[yum::default]", "recipe[apt::default]", "recipe[poise-hoist::default]", "recipe[vox-app::test_scaffold]", "recipe[bananastand-app::db]", "recipe[bananastand-app::default]", "recipe[bananastand-app::nginx]", "recipe[bananastand-app::opencv]", "recipe[bananastand-app::redis]", "recipe[bananastand-app::vox_app_update]"]]
       [2017-04-13T16:29:59+00:00] INFO: Run List expands to [yum::default@3.13.0 (8de42e8), apt::default@2.9.2 (aa7652c), poise-hoist::default@1.1.0 (ab43a7e), vox-app::test_scaffold@0.5.1 (03cc1c2), bananastand-app::db@0.3.2 (0a883e3), bananastand-app::default@0.3.2 (0a883e3), bananastand-app::nginx@0.3.2 (0a883e3), bananastand-app::opencv@0.3.2 (0a883e3), bananastand-app::redis@0.3.2 (0a883e3), bananastand-app::vox_app_update@0.3.2 (0a883e3)]
       [2017-04-13T16:29:59+00:00] INFO: Starting Chef Run for default-ubuntu-1204-vagrant
       [2017-04-13T16:29:59+00:00] INFO: Running start handlers
       [2017-04-13T16:29:59+00:00] INFO: Start handlers complete.
       [2017-04-13T16:29:59+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found:
       resolving cookbooks for run list: ["yum::default@3.13.0 (8de42e8)", "apt::default@2.9.2 (aa7652c)", "poise-hoist::default@1.1.0 (ab43a7e)", "vox-app::test_scaffold@0.5.1 (03cc1c2)", "bananastand-app::db@0.3.2 (0a883e3)", "bananastand-app::default@0.3.2 (0a883e3)", "bananastand-app::nginx@0.3.2 (0a883e3)", "bananastand-app::opencv@0.3.2 (0a883e3)", "bananastand-app::redis@0.3.2 (0a883e3)", "bananastand-app::vox_app_update@0.3.2 (0a883e3)"]
       [2017-04-13T16:30:00+00:00] INFO: Loading cookbooks [yum@3.13.0, apt@2.9.2, poise-hoist@1.1.0, vox-app@0.5.1, bananastand-app@0.3.2, brightbox-ruby@1.0.0, git@4.0.2, logrotate@1.5.0, nginx@2.7.6, percona@0.15.5, redisio@2.5.0, vox-unicorn@0.3.0, vox-percona@0.1.26, runit@1.8.0, ulimit@0.4.0, build-essential@2.4.0, openssl@7.0.1, seven_zip@2.0.2, mingw@2.0.0, windows@2.0.2, bluepill@2.4.3, ohai@2.1.0, yum-epel@0.7.1, 7-zip@1.0.2, rsyslog@6.0.1, packagecloud@0.3.0, dmg@3.1.1]

       ================================================================================
       Error Syncing Cookbooks:
       ================================================================================

       Unexpected Error:
       -----------------
       NoMethodError: private method `select' called for nil:NilClass

       Platform:
       ---------
       x86_64-linux


       Running handlers:
       [2017-04-13T16:30:00+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-04-13T16:30:00+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2017-04-13T16:30:00+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-04-13T16:30:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-04-13T16:30:00+00:00] ERROR: private method `select' called for nil:NilClass
       [2017-04-13T16:30:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

</details>

The stacktrace indicates that this is occurring while removing old files:
<details>

```
root@default-ubuntu-1204-vagrant:~# cat /tmp/kitchen/cache/chef-stacktrace.out
Generated at 2017-04-13 16:30:00 +0000
NoMethodError: private method `select' called for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/cookbook/synchronizer.rb:205:in `block in remove_deleted_files'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/cookbook/synchronizer.rb:199:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/cookbook/synchronizer.rb:199:in `remove_deleted_files'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/cookbook/synchronizer.rb:226:in `clear_obsoleted_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/cookbook/synchronizer.rb:147:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/policy_builder/policyfile.rb:190:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/policy_builder/policyfile.rb:153:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:511:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:57:in `load'
/opt/chef/bin/chef-client:57:in `<main>'
```

</details>

**Comment by lamont-granquist** [comment]
smells like cookbook manifests v2?

**Comment by thommay** [comment]
not in 12.19 it isn't :)

**Comment by directionless** [comment]
I think I'm running into the same issue. Same looking stacktrace. Chef `12.19.36` buried deep in a vagrant

**Comment by thommay** [comment]
This should've been fixed in #6129

**Comment by jerrywardlow** [comment]
Ran into the same issue, just tried updating to 12.20.3 and am still receiving the same error:

```
Generated at 2017-05-12 18:04:08 +0000
NoMethodError: private method `select' called for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/cookbook/synchronizer.rb:205:in `block in remove_deleted_files'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/cookbook/synchronizer.rb:199:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/cookbook/synchronizer.rb:199:in `remove_deleted_files'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/cookbook/synchronizer.rb:226:in `clear_obsoleted_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/cookbook/synchronizer.rb:147:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/policy_builder/expand_node_object.rb:223:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/policy_builder/expand_node_object.rb:83:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/bin/chef-client:26:in `<top (required)>'
/bin/chef-client:57:in `load'
/bin/chef-client:57:in `<main>'
```

**Comment by akitada** [comment]
@jerrywardlow That's because 12.20.3 does not include the fix.
The next release will.
