### ISSUE TITLE
windows_service resource prints ruby warnings from win32-service gem

### ISSUE THREAD

**Issue by flakzilla** [chef/chef#7335]
## Description
We are in the process of upgrading from chef-client 13.x to 14.x. We encountered an unexpected behavior in the 14.x client where the windows_service resource prints out a bunch of warnings from the win32-service-0.8.10 gem. The warnings all deal with one particular service (CDPUserSvc) which apparently is checked each time the windows_service resource is used in a recipe. As far as I can tell, these warnings are just warnings and don't actually cause the windows_service resource to not work properly. It's an annoyance to see the warnings in the run output though, makes it much harder to read the logs or STDOUT of a chef run quickly.

## Chef Version
chef-client 14.1.12

## Platform Version
Windows Server 2016 (long term servicing build 1607, w/ desktop experience)

## Replication Case
* Install Windows Server 2016 with desktop experience
* Install chef-client 141.12
* Define a recipe with example windows_service resource like the following example:
```
windows_service "W32Time" do
        action          [:configure_startup, :start]
        startup_type    :automatic
        run_as_user     'NT AUTHORITY\LocalService'
        run_as_password ""
end
```
* Run chef-client from an elevated command prompt on the server's desktop. Observe output similar to the sample below. The session ID appended to the CDPUserSvc service name will likely be different.

## Client Output

```
  * windows_service[W32Time] action configure_startupC:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-0.8.10/lib/win32/service.rb:1081:in `block in services' : C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-0.8.10/lib/win32/service.rb:1081: warning: constant ::Fixnum is deprecated
 (StructuredWarnings::BuiltInWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-0.8.10/lib/win32/service.rb:1088:in `rescue in block in services' : WARNING: Failed to retrieve description for the CDPUserSvc_5fa8f service. (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-0.8.10/lib/win32/service.rb:1101:in `rescue in block in services' : WARNING: Unable to get delayed auto start information for the CDPUserSvc_5fa8f service (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-0.8.10/lib/win32/service.rb:1159:in `rescue in block in services' : WARNING: Unable to retrieve failure actions for the CDPUserSvc_5fa8f service (StructuredWarnings::StandardWarning) (up to date)
  * windows_service[W32Time] action startC:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-0.8.10/lib/win32/service.rb:1088:in `rescue in block in services' : WARNING: Failed to retrieve description for the CDPUserSvc_5fa8f service. (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-0.8.10/lib/win32/service.rb:1101:in `rescue in block in services' : WARNING: Unable to get delayed auto start information for the CDPUserSvc_5fa8f service (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-0.8.10/lib/win32/service.rb:1159:in `rescue in block in services' : WARNING: Unable to retrieve failure actions for the CDPUserSvc_5fa8f service (StructuredWarnings::StandardWarning) (up to date)
```

## Stacktrace
No stacktrace, the issue does not result in an error condition.

**Comment by tas50** [comment]
This was fixed in win32-service here https://github.com/chef/win32-service/commit/7b1720fca8ae39a10368fe10b4918deddbd622b1. We just need to get that gem released and then bump our dep to fix that. Thanks for the report @flakzilla. These are annoying and easy to get rid of.

**Comment by flakzilla** [comment]
Well enough. We'll keep an eye on this and update to the newer client version when it becomes available. I can confirm the issue is still present in 14.2.

Speaking of, the 14.2 client spits a bunch of these out unexpectedly:
````
WARN: Using deprecated positional arguments for sign(), please update to keyword arguments (from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0-universal-mingw32/lib/chef/http/authenticator.rb:114)
````
Do you want another bug report for this?

**Comment by tas50** [comment]
That last one we already have a fix for. It's in master and that'll get resolved with 14.3's release.

**Comment by flakzilla** [comment]
Sounds good to me. Thanks for taking care of it.

**Comment by tas50** [comment]
Resolved by #7405
